# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# Google calendar configuration.yaml entry
google:
  client_id: !secret google_client_id_calendar
  client_secret: !secret google_client_secret_calendar
# FireTV
media_player:
  - platform: androidtv
    name: FireTV
    device_class: firetv
    host: 192.168.1.98
    adb_server_ip: 192.168.1.118
    adb_server_port: 5037
    get_sources: true
    apps:
      com.amazon.tv.launcher: "Fire TV"
      com.netflix.ninja: "Netflix"
      com.swishly.webtv.fireosplayer: "com.swishly.webtv.fireosplayer"
      com.google.android.youtube.tv: "Youtube"
      com.amazon.avod: "Amazon Video"
device_tracker:
  - platform: ping
    hosts:
      hostname: 192.168.1.98
